spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/luffy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: user
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
          cache: false
          check-template-location: true
          prefix: classpath:/templates/
          suffix: .html